export const ADD_ARCHIVED_START = 'ADD_ARCHIVED_START';
export const ADD_ARCHIVED_SUCCESS = 'ADD_ARCHIVED_SUCCESS';
export const ADD_ARCHIVED_FAILED = 'ADD_ARCHIVED_FAILED';

export const GET_ARCHIVED_START = 'GET_ARCHIVED_START';
export const GET_ARCHIVED_SUCCESS = 'GET_ARCHIVED_SUCCESS';
export const GET_ARCHIVED_FAILED = 'GET_ARCHIVED_FAILED';

export const DELETE_ARCHIVED_START = 'DELETE_ARCHIVED_START';
export const DELETE_ARCHIVED_SUCCESS = 'DELETE_ARCHIVED_SUCCESS';
export const DELETE_ARCHIVED_FAILED = 'DELETE_ARCHIVED_FAILED';
