export const ADD_STARRED_START = 'ADD_STARRED_START';
export const ADD_STARRED_SUCCESS = 'ADD_STARRED_SUCCESS';
export const ADD_STARRED_FAILED = 'ADD_STARRED_FAILED';

export const GET_STARRED_START = 'GET_STARRED_START';
export const GET_STARRED_SUCCESS = 'GET_STARRED_SUCCESS';
export const GET_STARRED_FAILED = 'GET_STARRED_FAILED';

export const DELETE_STARRED_START = 'DELETE_STARRED_START';
export const DELETE_STARRED_SUCCESS = 'DELETE_STARRED_SUCCESS';
export const DELETE_STARRED_FAILED = 'DELETE_STARRED_FAILED';
