export const ADD_FILE_START = 'ADD_FILE_START';
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS';
export const ADD_FILE_FAILED = 'ADD_FILE_FAILED';

export const GET_FILE_START = 'GET_FILE_START';
export const GET_FILE_SUCCESS = 'GET_FILE_SUCCESS';
export const GET_FILE_FAILED = 'GET_FILE_FAILED';

export const GET_LATESTFILE_START = 'GET_LATESTFILE_START';
export const GET_LATESTFILE_SUCCESS = 'GET_LATESTFILE_SUCCESS';
export const GET_LATESTFILE_FAILED = 'GET_LATESTFILE_FAILED';
